//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Coin_wav
    {
        public const string BundleName = "coin_wav";
        public const string COIN = "Coin";
    }
    public class Gamebg演艺人_mp3
    {
        public const string BundleName = "gamebg演艺人_mp3";
        public const string GAMEBG演艺人 = "GameBG演艺人";
    }
    public class Hit_wav
    {
        public const string BundleName = "hit_wav";
        public const string HIT = "Hit";
    }
    public class Icon_spriteatlasv2
    {
        public const string BundleName = "icon_spriteatlasv2";
        public const string ICON = "Icon";
    }
    public class Music
    {
        public const string BundleName = "music";
    }
    public class Sfx
    {
        public const string BundleName = "sfx";
        public const string ACHIEVEMENT = "Achievement";
        public const string BALL = "Ball";
        public const string BOMBEXPLOSION = "BombExplosion";
        public const string BUTTONCLICK = "ButtonClick";
        public const string DEATH = "Death";
        public const string ENEMYDIE = "EnemyDie";
        public const string EXP = "Exp";
        public const string HEALTH = "Health";
        public const string HOMEBG = "HomeBg";
        public const string HURT = "Hurt";
        public const string KNIFE = "Knife";
        public const string LEVELUP = "LevelUp";
        public const string RETRO_EVENT_ACUTE_08 = "Retro Event Acute 08";
        public const string RETRO_EVENT_ACUTE_11 = "Retro Event Acute 11";
        public const string RETRO_EVENT_UI_01 = "Retro Event UI 01";
        public const string TREASUER_CHEST = "Treasuer_chest";
        public const string WALK = "Walk";
    }
    public class Uigameoverpanel_prefab
    {
        public const string BundleName = "uigameoverpanel_prefab";
        public const string UIGAMEOVERPANEL = "UIGameOverPanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uigamepasspanel_prefab
    {
        public const string BundleName = "uigamepasspanel_prefab";
        public const string UIGAMEPASSPANEL = "UIGamePassPanel";
    }
    public class Uigamestartpanel_prefab
    {
        public const string BundleName = "uigamestartpanel_prefab";
        public const string UIGAMESTARTPANEL = "UIGameStartPanel";
    }
}
